[package]
name = "kernel_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bootloader_api = "0.11"
kernel = { path = "../kernel" }
kernel_test_framework = { path = "../kernel_test_framework" }